# Generated by Django 4.1 on 2022-08-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
