# Generated by Django 4.1 on 2022-08-11 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_comment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='website',
        ),
    ]
